# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}
# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - develop
    
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - ps: $Env:LABEL = $Env:APPVEYOR_REPO_BRANCH + "-" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

nuget:
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                  # account/project feeds for pull request builds

#-----------------------------------------------------------------#
# Build configuration.                                            #
#-----------------------------------------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build: off

# https://github.com/StevenLiekens/dotnet-core-appveyor

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build "src\Localization.JsonLocalizer" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
  - dotnet build "test\Localization.JsonLocalizer.Tests" -c %CONFIGURATION% --version-suffix %LABEL%

after_build:
  - dotnet pack "src\Localization.JsonLocalizer" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts

#-----------------------------------------------------------------#
# Test configuration.                                             #
#-----------------------------------------------------------------#

test: off

test_script:
  - dotnet test "test\Localization.JsonLocalizer.Tests" -c %CONFIGURATION% --no-build

artifacts:
  - path: artifacts\**\*.*
