# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}
# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - develop
    
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  # https://www.nimeshjm.com/building-asp-net-core-applications-in-appveyor/
  - nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
  - nuget sources list
  # Install dnvm
  - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
  # Install coreclr
  - dnvm upgrade -r coreclr
  - dnvm use coreclr
  - dnvm list
  # to run script as a PowerShell command prepend it with ps:
  - ps: Write-Host 'This is PowerShell'
  # batch commands start from cmd:
  - cmd: echo This is batch again
  - cmd: set MY_VAR=12345

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

