name: .NET Core

on:
  push:
    tags:
      - '*'
env:
  PROJECT_FILE: src/AspNetCore.Localization.Json/AspNetCore.Localization.Json.csproj 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ${{ env.PROJECT_FILE }}
    - name: Build
      run: dotnet build --configuration Release --no-restore ${{ env.PROJECT_FILE }}
    - name: Get release version
      id: get_release_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Pack
      run: >
        dotnet pack 
        --configuration Release 
        --no-build 
        --no-restore 
        --output $GITHUB_WORKSPACE/dist 
        -p:PackageId=Kowalew.AspNetCore.Localization.Json
        -p:PackageVersion=${{ steps.get_release_version.outputs.VERSION }}
        ${{ env.PROJECT_FILE }}
    - name: Push
      run: >
        dotnet nuget push
        --api-key ${{secrets.NUGETORG_PAT}}
        --source https://api.nuget.org/v3/index.json
        $GITHUB_WORKSPACE/dist/*.nupkg
